#!/bin/bash

version=$1

if [ -z "$version" ]; then
  echo "please specify the version as the first argument" >&2
  exit 1
fi

tags=

for i in $(seq 0 9); do
  tag=phjardas/testapp:${version}.${i}
  echo && echo "=== Building $tag ==="
  docker build --build-arg APP_VERSION=${version}.${i} --tag $tag .
  tags=$"${tags} ${tag}"
done

echo && echo "=== Built images ==="
echo "Now run the following lines to push them to Docker Hub:"
echo
for tag in $tags; do
  echo "docker push $tag";
done
